x = ["Anne", "Tom", "Susan", "John"]
x.append("Mark")
print("after append", x)
x.sort()
print("after sort", x)
x.remove("Susan")
print("after remove", x)
x.pop()
print("after pop", x)
x.insert(1, "Mark")
print("after insert", x)
print("after count ", x.count("Mark"))
print("after index ", x.index("John"))
x.reverse()
print("after reverse", x)
x.clear()
print("after clear ", x)